name: route_shuffle
description: "A route shuffle app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  dio: ^5.4.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  geolocator: ^11.0.0
  go_router: ^13.2.1
  easy_localization: ^3.0.5
  logger: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mockito: ^5.4.4
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
